name: guile-ci
on: push
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
    - name: step-one
      run: echo "Hello world!"
    - name: step-two
      run: sudo apt-get install -y guile-3.0
    - name: step-three
      run: guile -c "(display \"Hello world!\")"
    - name: step-four
      run: sudo apt-get install -y build-essential
    - name: step-five
      run: make --version
    - name: step-six
      run: pwd
    - name: step-seven
      run: cd "/2. Lesson № 2 - 19.02.24/1. HomeWorks № 1 - 20.02.24/"
    - name: step-eight
      run: ls -l
    - name: step-seven
      run: make makefile
